#!/bin/bash
#
# Daily_Archive - Archive designated files & directories
########################################################
#
# Gather Current Date
#
DATE='date +%y%m%d'
#
# Set Archive File Name
#
FILE=archive$DATE.tar.gz
#
# Set Configuration and Destination file
#
CONFIG_FILE=/home/liuwj-honliv/document/Files_To_Backup
DESTINATION=/home/liuwj-honliv/archive/$FILE
#
################## Main Script ########################
#
# Check Backup Config file exists
# 
if [ -f $CONFIG_FILE ] # Make sure the config file still exists.
then	# If it exists. do nothing but continue on.
    echo
else
    echo
    echo "$CONFIG_FILE does not exitst."
    echo "Backup not completed due to missing Configuration File"
    echo
    exit
fi
#
# Build the name of all the files to backup
#
FILE_NO=1    # Start on Line 1 of Config File.
exec < $CONFIG_FILE   # Redirect Std Input to name of Config File
#
read FILE_NAME        # Read 1st record
#
while [ $? -eq 0 ]    # Create list of files to backup
do
	#make sure the file or directory exists.
    if [ -f $FILE_NAME -o -d $FILE_NAME ]
    then 
        # if file exitsts, and its name to the list.
	FILE_LIST="$FILE_LIST $FILE_NAME"
    else
	# if file doesn't exist, issue warning
	echo 
	echo "$FILE_NAME, does not exist."
	echo "Obviously, I will not include it in this archive."
	echo "It is listed on line $FILE_NO of the config file."
	echo "Continuing to build archive list ..."
	echo
    fi
#
    GILR_NO=$[$FILE + 1] # Increase Line/File number by one.
    read FILE_NAME       # Read next record.
done
#
##############################################################
#
# Backup the files and Compress Archive
#
tar -czf $DESTINATION $FILE_LIST 2> /dev/null
#

